// <auto-generated />
using CIS174FinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIS174FinalProject.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260119164609_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CIS174FinalProject.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Harper",
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "George",
                            LastName = "Orwell"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "F. Scott",
                            LastName = "Fitzgerald"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "J.K.",
                            LastName = "Rowling"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "J.R.R.",
                            LastName = "Tolkien"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Jane",
                            LastName = "Austen"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Herman",
                            LastName = "Melville"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Leo",
                            LastName = "Tolstoy"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Charles",
                            LastName = "Dickens"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Mark",
                            LastName = "Twain"
                        });
                });

            modelBuilder.Entity("CIS174FinalProject.Models.Book", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ISBN");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ISBN = "978-0-06-112008-4",
                            AuthorId = 1,
                            GenreId = 3,
                            Title = "To Kill a Mockingbird",
                            Year = 1960
                        },
                        new
                        {
                            ISBN = "978-0-452-28423-4",
                            AuthorId = 2,
                            GenreId = 5,
                            Title = "1984",
                            Year = 1949
                        },
                        new
                        {
                            ISBN = "978-0-7432-7356-5",
                            AuthorId = 3,
                            GenreId = 3,
                            Title = "The Great Gatsby",
                            Year = 1925
                        },
                        new
                        {
                            ISBN = "978-0-439-13959-8",
                            AuthorId = 4,
                            GenreId = 4,
                            Title = "Harry Potter and the Sorcerer's Stone",
                            Year = 1997
                        },
                        new
                        {
                            ISBN = "978-0-618-00222-1",
                            AuthorId = 5,
                            GenreId = 4,
                            Title = "The Lord of the Rings",
                            Year = 1954
                        },
                        new
                        {
                            ISBN = "978-0-14-143951-8",
                            AuthorId = 6,
                            GenreId = 3,
                            Title = "Pride and Prejudice",
                            Year = 1813
                        },
                        new
                        {
                            ISBN = "978-0-14-243724-7",
                            AuthorId = 7,
                            GenreId = 3,
                            Title = "Moby-Dick",
                            Year = 1851
                        },
                        new
                        {
                            ISBN = "978-0-14-044793-4",
                            AuthorId = 8,
                            GenreId = 3,
                            Title = "War and Peace",
                            Year = 1869
                        },
                        new
                        {
                            ISBN = "978-0-14-143974-7",
                            AuthorId = 9,
                            GenreId = 3,
                            Title = "Great Expectations",
                            Year = 1861
                        },
                        new
                        {
                            ISBN = "978-0-14-039084-2",
                            AuthorId = 10,
                            GenreId = 3,
                            Title = "The Adventures of Huckleberry Finn",
                            Year = 1884
                        });
                });

            modelBuilder.Entity("CIS174FinalProject.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Science Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Classic Literature"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Dystopian"
                        });
                });

            modelBuilder.Entity("CIS174FinalProject.Models.Book", b =>
                {
                    b.HasOne("CIS174FinalProject.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CIS174FinalProject.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("CIS174FinalProject.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("CIS174FinalProject.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
